name: 'Install Required Modules'
description: 'Runs the Install-RequiredModule.ps1 script'
author: 'ALT3 B.V.'

inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  dataFile:
    description: 'Path to the RequiredModules.psd1 data file'
    required: false
    default: ${{github.workspace}}/RequiredModules.psd1

runs:
  using: 'node16'
  main: 'dist/index.js'
