name: 'Install Required Modules'
description: 'Runs the Install-RequiredModule.ps1 script'
author: 'ALT3 B.V.'

inputs:
  dataFile:
    description: 'Path to the RequiredModules data file'
    required: false
    default: ${{github.workspace}}/RequiredModules.psd1

runs:
  using: 'node18'
  main: 'dist/index.js'
