name: 'Test'

# rebuild any PRs and main branch changes
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # make sure build/ci work properly
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        run: |
          npm run test

  # make sure the action works on a clean machine without building
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          dataFile: 'dev/RequiredModules.psd1'
